version: 2

models:
  - name: cleansed_sales
    description: Cleansed sales data from raw_sales
    columns:
      - name: InvoiceNo
        tests:
          - not_null
      - name: StockCode
        tests:
          - not_null
      - name: Quantity
        tests:
          - not_null
      - name: CustomerID
        tests:
          - not_null
  - name: fact_sales
    description: Fact table for sales transactions
    columns:
      - name: InvoiceNo
        tests:
          - not_null
      - name: product_key
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: customer_key
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: total_amount
        tests:
          - not_null
  - name: dim_product
    description: Dimension table for products
    columns:
      - name: product_key
        tests:
          - unique
          - not_null
  - name: dim_customer
    description: Dimension table for customers
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
  - name: dim_date
    description: Dimension table for dates
    columns:
      - name: date_key
        tests:
          - unique
          - not_null